
MAPS = [
    {
        "name": "Map 1 \u00b7 Two rooms, table, door",
        "rows": [
            "##################",
            "#......#.........#",
            "#................#",
            "#......#.......F.#",
            "#......#######D###",
            "#......#.........#",
            "#......T.........#",
            "#......#.........#",
            "##################",
        ],
        "start": (7, 1),
        "tokens": [
            (1, 2, "Path."),
            (1, 3, "solid"),
            (1, 4, "="),
            (5, 10, "Door."),
            (5, 11, "open"),
            (5, 12, "="),
            (2, 10, "False"),
            (6, 3, "True"),
        ],
        "solution": [
            ("UUUUURRRRRRR", "Climb the left room and walk through the open gap into the top-right room."),
            ("URRRD", "Circle round False so you stand on its right side."),
            ("LLLLL", "Push False left, back through the gap, to the cell under the rule slot."),
            ("DLU", "Go under it and push it up: Path.solid = False (table vanishes)."),
            ("LLLDDDD", "Walk to the left of True, in the bottom of the start room."),
            ("RRRRRRRRRR", "Push True right through the old table cell into the bottom-right room."),
            ("DRU", "Slip under and push True up into the Door rule: Door.open = True."),
            ("RUUURR", "Through the door and on to the flag."),
        ],
    },
    {
        "name": "Map 2 \u00b7 Three rooms, NOT vault, trap",
        "rows": [
            "####################",
            "#.....#......#.....#",
            "#.....#......#.....#",
            "#.....#......#.....#",
            "#.....D......X...F.#",
            "#.....###T#T##.....#",
            "#.....#......#.....#",
            "#.....#......#.....#",
            "####################",
        ],
        "start": (7, 1),
        "tokens": [
            (1, 2, "Door."),
            (1, 3, "open"),
            (1, 4, "="),
            (4, 4, "True"),
            (7, 2, "Path."),
            (7, 3, "solid"),
            (7, 4, "="),
            (6, 5, "True"),
            (1, 8, "Trap."),
            (1, 9, "lethal"),
            (1, 10, "="),
            (6, 9, "NOT"),
            (3, 12, "True"),
        ],
        "solution": [
            ("UURRRRD", "Push False down into the Path rule: Path.solid = False. Both tables in the middle room are now walkable."),
            ("LLUURDRUUU", "Push the first True right, then up into the Door rule: Door.open = True."),
            ("DDRRRRRRDDDLL", "Through the door, cross the middle room and drop through a table gap into the vault, ending under NOT."),
            ("UUU", "Push NOT up out of the vault to the row 3."),
            ("LURRDRUU", "Push NOT right 2, then up 2 into the Trap rule slot."),
            ("DDRUU", "Go round the second True and push it up next to NOT: Trap.lethal = NOT True = False."),
            ("DDRRRRR", "Walk over the now-harmless trap and into the flag room."),
        ],
    },
    {
        "name": "Map 3 \u00b7 Serpentine vault",
        "rows": [
            "##################",
            "#.....#.....#....#",
            "#.....#.....#....#",
            "#.....####..#....#",
            "#.....T.....D...F#",
            "#.....#.##..#....#",
            "#.....#.....#....#",
            "#.....#.....#....#",
            "##################",
        ],
        "start": (7, 1),
        "tokens": [
            (2, 1, "Path."),
            (2, 2, "solid"),
            (2, 3, "="),
            (2, 5, "True"),
            (5, 4, "NOT"),
            (1, 7, "Door."),
            (1, 8, "open"),
            (1, 9, "="),
            (6, 10, "NOT"),
            (6, 11, "False"),
        ],
        "solution": [
            ("RRRUUUU", "Push the first NOT up into the Path rule: Path.solid = NOT True = False. The table in the gap disappears."),
            ("DRRR", "Walk through the old table cell into the vault."),
            ("DDDRRR", "Go down the left side and along the bottom to stand under the second NOT."),
            ("UUUUU", "Push NOT up through the wall opening into the Door rule."),
            ("DDDDDRUUUUU", "Go back down, shift one column right and push False up beside it: Door.open = NOT False = True."),
            ("DDRRRRR", "Down to the door row, through the open door and on to the flag."),
        ],
    },
    {
        "name": "Map 4 \u00b7 Swap the values",
        "rows": [
            "#################",
            "#...............#",
            "#...............#",
            "#...............#",
            "#...............#",
            "##.##############",
            "#......X...D...F#",
            "#################",
        ],
        "start": (6, 1),
        "tokens": [
            (2, 10, "Door."),
            (2, 11, "open"),
            (2, 12, "="),
            (2, 13, "False"),
            (2, 14, "True"),
            (1, 3, "Trap."),
            (1, 4, "lethal"),
            (1, 5, "="),
        ],
        "solution": [
            ("RUU", "Climb the gap from the corridor into the big hall."),
            ("RRRRRRRUUURRRR", "Walk to the top row, above the Door rule's False."),
            ("D", "Push False down out of the Door rule (Door.open is back to False for now)."),
            ("URRDDL", "Loop round the right side to stand right of False."),
            ("LLLLLLL", "Push False left along the bottom row of the hall, under the Trap rule."),
            ("DLUU", "Get beneath it and push it up into the Trap rule: Trap.lethal = False."),
            ("DRRRRRRRRRUL", "Cross to the right, get right of True and push it left into the empty slot: Door.open = True."),
            ("DDLLLLLLLLLLLLDD", "Head back to the gap and drop into the corridor."),
            ("RRRRRRRRRRRRR", "Walk over the harmless trap, through the open door, to the flag."),
        ],
    },
    {
        "name": "Map 5 \u00b7 Four chambers, three gates",
        "rows": [
            "#########################",
            "#.....#.....#.....#.....#",
            "#.....#.....#.....#.....#",
            "#.....#.....#.....#.....#",
            "#.....D.....T.....X....F#",
            "#.....#.....#.....#.....#",
            "#.....#.....#.....#.....#",
            "#.....#.....#.....#.....#",
            "#########################",
        ],
        "start": (7, 1),
        "tokens": [
            (1, 1, "Door."),
            (1, 2, "open"),
            (1, 3, "="),
            (6, 4, "True"),
            (4, 2, "True"),
            (6, 7, "Path."),
            (6, 8, "solid"),
            (6, 9, "="),
            (2, 9, "True"),
            (1, 13, "Trap."),
            (1, 14, "lethal"),
            (1, 15, "="),
            (6, 16, "NOT"),
        ],
        "solution": [
            ("RRRUUUUU", "Room 1: push True up into the Door rule (Door.open = True)."),
            ("LLLDD", "Walk round to the left of False."),
            ("RRRRRRRR", "Push False right, through the now-open door, to the middle of room 2."),
            ("URDD", "Get above it and push it down into the Path rule: Path.solid = False. The table gate opens."),
            ("UUUULDD", "Go up to the top row and push the second True down to row 4."),
            ("LDRRRRRRRR", "Get left of that True and push it right through the table cell into room 3 (far right column)."),
            ("LDDDRUUUUU", "Loop under it and push NOT up into the Trap rule slot."),
            ("DDDRUUU", "Go round and push True up beside NOT: Trap.lethal = NOT True = False."),
            ("DDRRRRRR", "Cross the harmless trap into room 4 and reach the flag."),
        ],
    },
    {
        "name": "Map 8 · Vault cathedral · sealed door",
        "rows": [
            "############################################",
            "#.............#.............#.......#.#....#",
            "#.........#...#.............#.......#.#....#",
            "#.............#.......M.....#.......#.#....#",
            "#.............D.............T.......X.D.XF.#",
            "#.............#.............#.......#.#....#",
            "#.M...M...M...BBBBBBBBB.M.M.#.#T#T#.#.#.M.M#",
            "#.....S.....#.B.......B.#...#.#...#.#.#....#",
            "#...MS.SM...M.B.M...M.B.M.M.#.#.M.###.#.M.M#",
            "#.....S...#...B.......B.....#.#...#.#.#....#",
            "#.M...M...M...BBBBBBBBB.M.M.#.#####.#.#.M.M#",
            "############################################",
        ],
        "start": (9, 2),
        "tokens": [
            (2, 3, "Door."), (2, 4, "open"), (2, 5, "="),
            (8, 6, "True"),  (4, 3, "False"),
            (2, 17, "Stone."), (2, 18, "solid"), (2, 19, "="),
            (2, 30, "Trap."), (2, 31, "lethal"), (2, 32, "="),
            (7, 33, "NOT"), (6, 8, "True"),
            (9, 15, "Seal."), (9, 16, "active"), (9, 17, "="),
            (9, 19, "True"), (8, 18, "NOT"),
        ],
        "solution": [
            ("RUUUURUURRUURRRRRRRRRRD",
             "Vault: push NOT down into the Seal rule: Seal.active = NOT True = False."),
            ("ULLLDDDDLLDDLLLLDLDLUUUUULURDRU",
             "Room 1: push NOT up into the Door rule: Door.open = NOT sealed = NOT False = True."),
            ("LLLLDRRRRRRRRRRRRRRRRRDRUU",
             "Push False through the open door and up into the Stone rule: Stone.solid = False."),
            ("DRRRRRRRRRDRRDDDDRRUUUUUU",
             "Enter the trap vault through a stone cell and push NOT up into the Trap rule slot."),
            ("DLLLLLLLLLLLLLLLLLLLLDLLDDLLLUULURRRRRRRRRRRRRRRRRRRRRRRRRRDRUU",
             "Carry True through the door to sit beside NOT: Trap.lethal = NOT True = False."),
            ("DRRRRRRR",
             "Walk over the harmless traps, through the second door, to the flag."),
        ],
        "warp": [[1, 13, 7, 15]],
    },
    {
        "name": "Map 10 · The Relocating Flag (L6)",
        "rows": [
            "##################################################",
            "#M.M...M.M..B...M.....M.B...........B...B........#",
            "#...........B...........B...........B.M.B........#",
            "#M#.........B.........#.B.H.....H...B.#.B...#M...#",
            "#.........#.B.......#...B..#.....#..B...B........#",
            "#M..........B...M.....M.B...........B...B..M...B.#",
            "#...........D...........X...........T...D..X..BFB#",
            "#M..........#...........#.H...#.H...B...BM.....B.#",
            "#.........#.B...........B...........B...B........#",
            "#M..........B.#......#M.B.#......#..B.#.B...#....#",
            "#...........B...........B...........B.M.B........#",
            "#M.M...#.M..B...........B.H.....H...B...B....M...#",
            "##################################################",
            "#.....................................BBBBBBBBBB.#",
            "#..............................H......B..H.HT..B.#",
            "#...........#.......................#.B...H.T..B.#",
            "##.H.......H....#.....................B.H...T..B##",
            "#..............................H......BBBBBBBBBB.#",
            "##################################################",
        ],
        "start": (9, 2),
        "tokens": [
            (2, 2, "Door."), (2, 3, "open"), (2, 4, "="), (2, 5, "False"),
            (9, 8, "True"), (10, 3, "True"),
            (2, 14, "Trap."), (2, 15, "lethal"), (2, 16, "="),
            (9, 17, "NOT"),
            (8, 28, "Stone."), (8, 29, "solid"), (8, 30, "="),
            (10, 29, "Wall."),
            (14, 5, "solid"), (14, 6, "="),
            (16, 7, "False"),
            (14, 20, "Flag."), (14, 21, "moved"), (14, 22, "="),
            (11, 14, "True"),
        ],
        "solution": [
            ("RUUUUUURRRUULDDDLDDDDDLLDRRRDRUUUUUUUURULRRRRRDDDDRRRRRDDDDRUUUUUUUDDDLLLLLLDDDDLLLUUULURRRRRRRRRRDRUUUURRRDRRDDRRRRDDDRUDRRDLDLUULUUULLLLLLLLLLLLLLLLULLULLLLDLDRRRRRRRRRURDLDRRRRRRRRRDRULURRRRRRRRURDD",
             "Original relay: open the door, disarm the trap, then rebuild the Wall rule so Wall.solid = False (plain walls become passable). The fuse idea is gone; the visible flag is now a decoy sealed behind mines."),
            ("ULLLLDDDDDDDDDDDLLLLLLLLLLLLLLLLLLLLUU",
             "Cross the floor wall into the new lower hall. Push its spare False into the Stone rule: Stone.solid = False. Every stone, including the wall of stones inside the hidden chamber, vanishes."),
            ("RUUURRRRRURRRRRRRRRURDDD",
             "Climb back into the first hall (plain walls are passable now). Push the spare True from its corner east along the floor to column 23, then drop it down through the floor wall into the Flag rule: Flag.moved = True. The flag leaps out of its mine ring into the isolated chamber."),
            ("LLLLDDDDLLLLLLLLLLLLLLLLLL",
             "The chamber has no door. Run down and west along the bottom edge to the hidden portal pad in the bottom-left corner nook (the pad in the top-right corner is a decoy)."),
            ("DRRDRRURRR",
             "Weave through the hidden always-lethal mines (they stay armed after the trap is disarmed), pass the vanished stones and step on the relocated flag."),
        ],
        "warp": [[17, 1, 14, 39], [13, 48, 17, 30]],
        "f2": [15, 46],
    },
    {
        "name": "Map 14 \u00b7 The Forge Citadel: craft Gate. (Access + point \u2192 entry + turn), a sealed at, portal-only finish, three seals, a laser-guarded Seal3 room (L6)"
        ,"rows": [
            "####################################################",
            "#BBBBBBBBBM......#................#................#",
            "#BM.M.M.MB......###H.....#........#...............##",
            "#B.......BM......#................#......H.......H.#",
            "#B.......B.......#..........H.#...#.......BBBBBBB..#",
            "#BBBBBBBBBM......#................#BBBBBBBB.....B..#",
            "#.....M##........#..........#.....#B.....BB.....B..#",
            "#................#................#B.....BB.....BH.#",
            "#.M.....M........#.H..............#B.....BBBBBBBB..#",
            "#................D................#BBBBBBB.........#",
            "#...M.....M......#.....BBBBBBBBB.##.....#..........#",
            "#........BBBBBBB.#.....B.......B..#..BBBBBBBBBB....#",
            "#.....M..B.....B.#.....B.......B..#..B........B....#",
            "#........B.....B.#.....B#......B..#..B........B....#",
            "#........B.....B.#.H...L.......B..#..B........B...##",
            "#........BBBBBBB.#.....BBBBBBBBB..#..BBBBBBBBBB....#",
            "#................#...#......H.#...#................#",
            "#.M...M...M.#....#...........#....#................#",
            "####################################################",
            "#..................................................#",
            "#.BBBBBBBBBBBBBBBBBBBB............BBBBBBBBBBBBBBBBB#",
            "#.B.......SSS........B............B........B....H.B#",
            "#.B.......S.S........B.........H..B........B......B#",
            "#.BYYY....SSS........B....ZZZ.....E........T....H.B#",
            "#.BY.Y...............B....Z.Z..H..B........B......B#",
            "#.BYYY...............B....ZZZ.....B.....H.HB....H.B#",
            "#.BBBBBBBBBBBBBBBBBBBB.........H..BBBBBBBBBBBBBBBBB#",
            "####################################################"
        ],
        "start": [3, 3],
        "tokens": [[14, 10, 'Trap.'], [14, 11, 'lethal'], [14, 12, '='], [14, 14, 'True'], [13, 13, 'NOT'], [4, 8, 'Door.'], [4, 9, 'open'], [4, 10, '='], [4, 12, 'False'], [7, 11, 'NOT'], [4, 20, 'Wall.'], [4, 21, 'solid'], [4, 22, '='], [4, 24, 'True'], [8, 23, 'NOT'], [21, 24, 'Latch.'], [21, 25, 'open'], [21, 26, '='], [21, 28, 'False'], [24, 27, 'NOT'], [21, 36, 'Stone.'], [21, 37, 'solid'], [21, 38, '='], [21, 40, 'True'], [24, 39, 'NOT'], [22, 4, '@Door'], [22, 7, 'OR'], [22, 11, '@Trap'], [25, 17, '='], [25, 18, 'True'], [7, 43, 'Seal.'], [7, 44, 'active'], [7, 45, '='], [7, 47, 'True'], [6, 46, 'NOT'], [12, 39, 'Seal2.'], [12, 40, 'active'], [12, 41, '='], [12, 43, 'True'], [13, 42, 'NOT'], [24, 4, 'at'], [12, 25, 'Seal3.'], [12, 26, 'active'], [12, 27, '='], [12, 29, 'True'], [13, 28, 'NOT'], [6, 36, 'Laser.'], [6, 37, 'beams'], [6, 38, '='], [6, 40, 'True'], [7, 39, 'NOT']],
        "rec": [['@Door', 'OR', 'Entry'], ['Entry', '@Trap', 'Gate.']],
        "f2": [13, 44],
        "warp": [[4, 7, 13, 4], [1, 16, 12, 10], [17, 16, 5, 13], [1, 50, 12, 38], [17, 35, 25, 23], [23, 46, 23, 19], [17, 50, 3, 48], [9, 44, 5, 43], [2, 37, 8, 36]],
        "solution": [['DRRRR', 'You start in a sealed chamber ringed by striped mine walls. Search it: one hidden cell is a portal out into the west hall.'], ['DDRDRRRRRRRRDRRRUUUURRR', 'West hall: a vault holds the Trap rule. Its portal hides in the top-right corner nook.'], ['RRRD', 'NOT down: Trap.lethal = NOT True = False. Every mine is disarmed.'], ['ULLL', 'Step on the pad again to leave the vault.'], ['LDDDDDDDLLLLUUU', 'NOT up into the Door rule: Door.open = NOT False = True.'], ['DDDDRRRRRRR', 'Through the door into the middle hall.'], ['RRRRRUUUU', 'NOT into the Wall slot: Wall.solid = NOT True = False. Plain walls are now passable (striped ones never are).'], ['RRUUURRRRRRRRRRRRRRRUDLLLDDLLLDLLLLLLLLLLL', 'Laser vault: with plain walls passable, go to the hidden 🌀 pad in the north-west of the east hall. It drops you into a sealed room with no door. Push its NOT up into the slot: Laser.beams = NOT True = False. Step back on the pad to leave, then return to the middle-hall corridor. The red laser door of the Seal3 room is now off.'], ['DDDDLDDDDDRRRRRRUDLLLLLLUUUUUUUUUR', "Third seal switch: the Seal3 rule now sits in a mine-walled room in the middle hall. Walk in through the (now dead) laser door and push the spare NOT up into the slot: Seal3.active = NOT True = False. The amber ring around the Forge's at block is now open. Then return to the middle-hall corridor."], ['DDDDRRRRRRRRRDRRRRRRRRRRURRRRRDULLLDLLLLLLLLLLUUUUULLLLLLLLLLL', "Seal vault: the plain walls are passable now, so cross the middle hall and the east hall to the hidden 🌀 pad in the row under the striped vault. It drops you inside. Push its NOT down into the slot: Seal.active = NOT True = False. Step back on the pad to leave, then return to the middle hall. The sealed ring around the Forge's turn block is now open."], ['RRUUUURRRRRRRRRRRRRRRRRRRRRRRRRDDRRRRULLLLUDLLLLLLLLLLDDLLLLLLDLLLLLLLLLLL', 'Second seal vault: with walls passable, go to the hidden pad in the north-east corner nook. It drops you into the finish chamber (the flag does not exist yet). Push its NOT up into the slot: Seal2.active = NOT True = False. Step back on the entry pad to leave, then return to the middle hall. The teal ring around the spare NOT in the switch hall opens.'], ['DDDDLDDDDDDDDDDDDDDDRRDRRRUUU', 'Drop through the plain wall into the lower level. In the switch hall push the spare NOT up into the Latch rule: Latch.open = NOT False = True. The pink latch door in the divider wall unlocks.'], ['DRRRRRRRRDDRRRRUUU', 'Through the latch door into the back room. Push its NOT up into the Stone rule: Stone.solid = NOT True = False. The stone wall vanishes.'], ['DRRRRRRRUD', 'Past the vanished stone to the last chamber. The hidden pad in it drops you into the Forge, an isolated vault. (A decoy pad in the south-west nook of the east hall only leads back to the switch hall.)'], ['UDLLLLLLLLLLLLLLLLURRRRRRR', 'Craft Gate.: push Access east into point to make entry, then keep pushing entry east into the turn (its ring is open) to make Gate.'], ['DLLLLLLLDRRRRRRRRRRRRURD', 'Deliver at: push the freed at block (its amber ring is open) east along row 24, then down from above into the slot right before the = block.'], ['UUULLLLLDDDLDRRRR', 'Deliver Gate.: push Gate. down to the bottom row, then east until it sits next to at. Gate.at = True: the finish line is generated.'], ['UURRRRR', 'Step onto the pad: it returns you to the back chamber of the lower level.'], ['LLLLLLLLLLLLLUUUUURRRURRRRRRRRRRRRRRUURR', 'Walk to the hidden pad in the north-east corner nook. It drops you inside the finish chamber (mine walls all around, no other way in).'], ['DRRRRRR', 'Step onto the finish line.']]
    },
    {
        "name": "Map 16 · Nested vaults, sealed walls & a timing window (L6)",
        "rows": [
            "##############################################",
            "#.....................#.BBBBBBB...BBBBBBBB...#",
            "#.............#.......#.B.....B...B......B...#",
            "#M...M...M...M...M...##.B.....B...B......B...#",
            "#.....................#.B.....B...B......B.#.#",
            "#.......#..........#..#.BBBBBBB...BBBBBBBB...#",
            "#M...M...M...M...M....#.......M...M...M...M..#",
            "#..................#..D......................#",
            "#.....................#.#####.M...M...M...M..#",
            "#M...M...##..M...M....#.#...#.......#........#",
            "#.....................#.#...#.....M#..M...M..#",
            "#.....................#.#...#................#",
            "#M...M...M..#M...M#...#.#####.M...M...M...M..#",
            "#.....................#..............#.......#",
            "######################BBSBBBBBBBBBBBBBBBBBBBB#",
            "#.........................T...D.....X....S.YF#",
            "#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB#",
            "#.........B....B....................BBB......#",
            "#.........Z....B..................M...M...M..#",
            "#.........B...................BBBBBBBBB...B..#",
            "#..BB...M.B.....BBBBM...M...M.B.......B.M.B.M#",
            "#....BB...B.Z.................B.......B...B..#",
            "#.......BBBZ.ZM...M...M.BBBB..B.......B...B..#",
            "#.........B.Z.................B.......B......#",
            "#.......M.B.M...BBBBM.........B.M...M.B.M...M#",
            "#......BBBB...................BBBBBBBBBBBBBB.#",
            "#.........B...M...M...M...M.BBM...M...MB..MB.#",
            "#.....BB..B.................BB.........BBBBB.#",
            "##############################################",
        ],
        "start": [11, 3],
        "tokens": [[2, 3, 'Stone.'], [2, 4, 'solid'], [2, 5, '='], [2, 7, 'True'], [6, 6, 'NOT'], [4, 10, 'Wall.'], [4, 11, 'solid'], [4, 12, '='], [8, 15, 'False'], [4, 25, 'Trap.'], [4, 26, 'lethal'], [4, 27, '='], [4, 29, 'True'], [3, 28, 'NOT'], [4, 35, 'Door.'], [4, 36, 'open'], [4, 37, '='], [3, 38, 'True'], [22, 31, 'Seal2.'], [22, 32, 'active'], [22, 33, '='], [22, 35, 'True'], [23, 36, 'NOT'], [18, 8, 'NOT'], [26, 2, 'Seal3.'], [26, 3, 'active'], [26, 4, '='], [26, 6, 'True'], [18, 26, 'Seal.'], [18, 27, 'active'], [18, 28, '='], [24, 25, 'NOT'], [18, 30, 'True']],
        "warp": [[10, 26, 2, 25], [2, 29, 2, 35], [12, 2, 3, 18], [12, 43, 8, 33], [13, 32, 18, 22], [13, 25, 26, 40], [22, 12, 20, 31]],
        "solution": [['UUUURRRUUUU', 'NOT up into the Stone rule: Stone.solid = NOT True = False (the stone vanishes).'], ['DDDDDRRRRRRRRDRUUUURULL', 'Push False up, then left, into the Wall rule: Wall.solid = False, so plain walls become passable.'], ['DDDDDDRRRRRRRRRRRR', 'Cross the dividing walls into the plain-wall chamber and step on the hidden pad at its centre.'], ['RRRDUR', 'Push NOT down: Trap.lethal = NOT True = False. Then step on the corner pad into the second vault.'], ['RLLLLL', 'The Trap rule is now False but the Door is still shut, the Seal rule is not yet completed, so the teal seals stay shut for now. Leave the vaults through the pads (hidden pads only show when you step on them).'], ['DDDRRRRRR', 'Hidden pad in the bottom row of the east hall (column 32) drops you into the south wing. (Column 25 in that row is a decoy that leads to a mine cell.) Read the Seal rule beside the arrival pad.'], ['DRDDDDDRRRRRDRUUUUUULLLLLLLLLLLLLLLULLLLLLLLLLL', 'Go down to the loose NOT in the lower hall, push it right along row 24 to column 29, walk under it and push it straight up the column into the Seal rule: Seal.active = NOT True = False, so the teal gates open. Then go back and on to the west chamber. The west chamber behind the teal gate holds a Seal3 rule and a loose NOT. Mines stop a pushed token (you can walk over them now that the Trap is off). Push the NOT left along the top row; the mine strip below blocks a straight drop.'], ['ULDDDDDD', 'Go round to the top and push it down the only mine-free column.'], ['LDRRR', 'Get below-left of it and push it right along row 24 to the column of the slot.'], ['URDD', 'Step above it and push it down into the slot: Seal3.active = NOT True = False. The amber seal in front of the flag opens.'], ['UUURRUUUURRRRDDDDR', 'Now the teal ring around the pad (still open while Door is shut and Trap is off). The pad drops you into the striped vault with the Seal2 rule.'], ['DRRRRRDRDLLDLURRUUULLLLL', 'Here the NOT starts in the corner: push it left along row 23, then walk under it and push it up into the slot. Seal2.active = NOT True = False, so both purple seals open. Step back on the pad.'], ['UUURRRRURRRRRR', 'Walk out through the teal ring and back onto the arrival pad to return to the east hall.'], ['UUULLLLLLRRRR', 'Back through the first vault to the Door vault (corner pad). Do this BEFORE opening the Door, but only now that the Seal2 is done.'], ['RRRD', 'Push True down into the Door rule: Door.open = True.'], ['ULLLLLLL', 'Take the pads back out through the first vault to the chamber.'], ['DDLLDDDRRRRRRRRRRRRRRRRRRRR', 'Everything is unlocked: Stone gone, Door open, Trap harmless, Seal2 open. The corridor gap and both purple seals plus the amber seal no longer block you; walk the striped-walled corridor to the flag.']],
    },
    {
        "name": "Map 17 extended Undercroft seals 4-6 four levers isolated finish",
        "rows": [
            "##############################################################",
            "#BBBBBBB....MMM..#.H.....H..H.....B................#.........#",
            "#B.....B....MVM..#..........H.H...#.....BBBBBBBBB..#.BBBBBBBB#",
            "#B.....B....M.M..#................#.....B.......B..#.B......B#",
            "#B.....B.........#....H.H....H.H..#.....B.......B..#.B..YYY.B#",
            "#BBBBBBB.........#....H.H.........#.....B.......B..#.B..Y.Y.B#",
            "#................#................#.....BBBBBBBBB..#.B..YYY.B#",
            "#...M..M.........#................#...H............#.B......B#",
            "#................#......H...H..H..#....H.....H.....#.B......B#",
            "#..M..M......MM..D................#...H.BBBBBBBBB..#.B......B#",
            "#................#................#.....B..ZZZ..B..#.BBBBUBBB#",
            "#..M....BBBBBBBBB#...BBBBBBBBB....#..H..B..Z.Z..B..#..HHH.H..#",
            "#.......B.......B#...B.......B....#...H.B..ZZZ..B..#.H.....H.#",
            "#..M..M.B.......B#...L.......B....#..H..B.......B..#.....H...#",
            "#.......B.......B#...B.......B....#.....B.......B..#.........#",
            "#..M..M.BBBBBBBBB#...BBBBBBBBB....#.....BBBBBBBBB..#.........#",
            "#..........M.....#......H..H......#.......H.H.H....#.........#",
            "#................#................#................#.........#",
            "##############################################################",
            "#BBBBBBBB.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB#",
            "#.......B..........B...................B.......MNM...........#",
            "#..SSS..B...H......B..............H....B.....HHM.M........H..#",
            "#..S.S.............B....H....PPPP...H..B.H..H.....H..H.......#",
            "#..SSS..B...H......B.........P..P......B.......BH..........H.#",
            "#.......B.BBBB.BBBBB.........PPPP......B.......B....H...WWW..#",
            "#.......B..........E...................T..QQQ..B........W.W..#",
            "#.....H.B.......H..BBBBBBBB.BBBBBBBBBBBB..Q.Q...........WWW..#",
            "#.......B..HHH.H...B....HHH.H..........B..QQQ..B..HHH.H......#",
            "#...H...B.H.....H..B...H.....H.H.......B.......B.H.....H.....#",
            "#.......B.....HH...B.......H.....H.....B.......B.....H.......#",
            "#..H....B..........B..H................B.....H.B........H....#",
            "#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBWBBBBBBBBBBBBBBBBBBB#",
            "#BBBBBBBBBBBBBBBBBBBBB................B......................#",
            "#BBBBBBBBBBBBBBBBBBBBB................B............BBBBBB....#",
            "#BBBBBBBBBBBBBBBBBBBBB....H...........B............B.........#",
            "#BBB..K.........BBBBBB................B............BBBBBB....#",
            "#BBB........H...BBBBBB............H...B........H.............#",
            "#BBB.....H......BBBBBB................B.....H.............H..#",
            "#BBBBBBBBBBBB...BBBBBB..H.............B.....HHHHH............#",
            "#BBB........H.H.BBBBBB................B....H.....H...........#",
            "#BBB........H..HBBBBBB................B................H.....#",
            "#BBB........HHH.BBBBBB......H................................#",
            "#BBBBBBBBBBBBBBBBBBBBB............................H..........#",
            "#BBBBBBBBBBBBBBBBBBBBB.......................................#",
            "##############################################################",
        ],
        "start": [3, 3],
        "tokens": [[14, 9, 'Lever.'], [14, 10, 'active'], [14, 11, '='], [14, 13, 'False'], [13, 12, 'NOT'], [4, 10, 'Door.'], [4, 11, 'open'], [4, 12, '='], [4, 14, 'False'], [3, 13, 'NOT'], [6, 20, 'Wall.'], [6, 21, 'solid'], [6, 22, '='], [6, 24, 'True'], [5, 23, 'NOT'], [14, 22, 'Seal3.'], [14, 23, 'active'], [14, 24, '='], [14, 26, 'True'], [13, 25, 'NOT'], [5, 41, 'Laser.'], [5, 42, 'beams'], [5, 43, '='], [5, 45, 'True'], [4, 44, 'NOT'], [14, 41, 'Seal.'], [14, 42, 'active'], [14, 43, '='], [14, 45, 'True'], [11, 44, 'NOT'], [8, 54, 'Seal2.'], [8, 55, 'active'], [8, 56, '='], [8, 58, 'True'], [5, 57, 'NOT'], [1, 20, 'Lever2.'], [1, 21, 'active'], [1, 22, '='], [1, 24, 'False'], [2, 23, 'NOT'], [1, 29, 'Lever3.'], [1, 30, 'active'], [1, 31, '='], [1, 33, 'False'], [11, 57, 'NOT'], [12, 54, 'Seal4.'], [12, 55, 'active'], [12, 56, '='], [12, 58, 'True'], [22, 4, 'NOT'], [28, 11, 'Latch.'], [28, 12, 'open'], [28, 13, '='], [28, 15, 'False'], [23, 30, 'NOT'], [23, 31, 'NOT'], [28, 24, 'Stone.'], [28, 25, 'solid'], [28, 26, '='], [28, 28, 'True'], [21, 48, 'NOT'], [22, 45, 'Seal5.'], [22, 46, 'active'], [22, 47, '='], [22, 49, 'True'], [26, 43, 'NOT'], [28, 50, 'Seal6.'], [28, 51, 'active'], [28, 52, '='], [28, 54, 'True'], [25, 57, 'NOT'], [39, 44, 'Lever4.'], [39, 45, 'active'], [39, 46, '='], [39, 48, 'False'], [37, 30, 'Beacon.'], [41, 57, 'lit'], [33, 26, '='], [36, 53, 'True'], [36, 6, 'False']],
        "warp": [[2, 6, 7, 10], [12, 15, 10, 14], [3, 47, 8, 38], [14, 47, 12, 37], [9, 54, 13, 56], [42, 24, 36, 6], [21, 15, 29, 3], [21, 22, 29, 36], [32, 60, 43, 60]],
        "f2": [40, 14],
        "solution": [
            ["RRRU", "Sealed start room: the only way out is a hidden \ud83c\udf00 pad inside it. It drops you in the west hall. Every mine in this map (\u2739) is permanent: the route never touches one."],
            ["DDDRRRRLLLDRRRU", "Lever vault: enter by the hidden pad. Drop NOT into the Lever slot: Lever.active = NOT False = True. Far away, the lever \ud83d\udd79\ufe0f behind the Door rule's mine-ringed NOT pulls and shoves that NOT down into its slot: Door.open = NOT False = True. You never touch the mines. Step on the pad to leave."],
            ["RURRR", "The Door is open: walk through it into the middle hall."],
            ["UUUUUURRRRRDD", "Walk down the safe lane between the H mines and push NOT into the Wall slot: Wall.solid = False. Plain walls are passable; striped walls and the border never are."],
            ["UURRDDDDRRRRRRRDRRRRRRLLLDRRRU", "Laser vault in the east hall: its pad hides in a mine nook. Laser.beams = NOT True = False. Leave by the pad."],
            ["LDDLLLLLLLLLLLLLLLLLDDDRRURRRD", "The red laser door of the Seal3 room is dead: walk in and push NOT: Seal3.active = False. The amber rings (\ud83d\udd0f) open: this frees the NOT in the finish chamber and the lit block in the Beacon forge."],
            ["LLLLLDDDDRRRRRRRRRRRRRRRRRRRRRRRRRRRURRUUURRRRRRRRRRUUULUURDDDRRDDLLLLL", "Finish chamber (east wing, pad hidden in the open): its Seal2 NOT sits behind the now-open amber ring. Seal2.active = False. The teal rings (\ud83d\udd10) open: this frees the NOT in the Seal vault and the Beacon. block in the forge."],
            ["DDDDLLLLLLLLLLLLLLLULLUULLLUURUUUULLLDDDRRDR", "Seal vault: cross the teal ring, push NOT down 3 cells: Seal.active = False. The purple rings (\ud83d\udd12) open: this frees the Latch NOT."],
            ["LUUUUUUUUULLLLLLLLLLLLLU", "NORTH HALL \u2013 Lever2. In the Signal Room a NOT is walled in by mines beneath a lever (U). Push the loose NOT (north hall, row 1) up into Lever2.active = [ ] False: Lever2 fires and the lever shoves the pocket NOT into Seal4.active = [ ] True. Seal4 = False, so every green ring (\ud83d\udee1\ufe0f) in the Gallery will dissolve."],
            ["DLLDDLLDDDDDDDDDDDDDLLLLLLLLLLDDDDLLULLLLDRRRRRRRRRRURDDDDDD", "ANTECHAMBER \u2013 drop through the single plain-wall gap in the lower ceiling. Free the NOT from the purple ring (Seal is already False), send it east through the 1-cell gap in the divider, then down the mine-lined lane into Latch.open = NOT False. The latch door (east wall) opens."],
            ["UURRRRRRUURRRRRURRRRRDDRDLLLULDDD", "GALLERY \u2013 the green ring holds TWO NOTs. Take the west one out through the ring, along row 23 and down the gap in the floor divider into Stone.solid = NOT True. The stone wall in the east wall dissolves."],
            ["UUUUURRRRDDRDLLLLLLLLLLLLLLLLLLLLLLDLUUUUUUUULURRRRRRRRRRRRRRRRRRRRRRR", "HAUL \u2013 the second NOT is not for this level. Push it back west through the latch door, up the chute above the Antechamber and out into the upper level, then east along the open row 17 under the whole map."],
            ["DRUUUUUUUUUUUUUUUU", "NORTH HALL \u2013 lift the NOT up lane 32 into Lever3.active = NOT False. Lever3 fires inside the Vault (far below) and shoves the pocket NOT into Seal5.active. Seal5 = False: the pink ring dissolves."],
            ["DDDDDDDDDDDDDDDDLLLLLLLLLLLLLLLLLLLLLLLDDDDDDDRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRDRRRRRRRRRRRRURDD", "VAULT \u2013 through the open stone door. The pink ring\u2019s NOT travels east through the divider gap (row 26), then down into Seal6.active = NOT True. Seal6 = False: the sky ring and the chute gate open."],
            ["UUURRRRDRDLLLLLLLLLLLLLLLLULDDDDDDDDDDDDDDLDRRRRRRDRU", "VAULT \u2192 FORGE \u2013 push the sky-ring NOT out along the row-26 gap, then south down the chute (col 41) through the open gate, across the forge and up into Lever4.active = NOT False. Lever4 fires inside the sealed finish chamber and shoves the blocker off the far end of the hidden pad."],
            ["DLLLLLLLLLLUUUULLLLULLLDDDDLDRRRRRRRRRRRRRRRRRRRRRRDRUUUULURRRRRDRUUURULLLLL", "BEACON 1/4 \u2013 the rule is built inside a dead-end corridor, so the order is forced. Push Beacon. through the gap and all the way to the end of the corridor (row 34)."],
            ["RRRRDDDDDDLDDRUUUUUUURULLLL", "BEACON 2/4 \u2013 push lit in behind it."],
            ["RRRDDDDDDDLLLLLLLLLLLLLLLLLLLLUUUUUULLLLLLLLLLLLUURRRRURDDDDDDDDLDRRRRRRRRRRRRRRRRRRRRRRRRRRRDRUUUUUUURULLL", "BEACON 3/4 \u2013 then the = sign."],
            ["RRDDDLLLLLURRRRDRUURULL", "BEACON 4/4 \u2013 finally True. Beacon.lit = True: the flag is generated in the isolated finish chamber."],
            ["RDDDDDDDLLLLLLLLDLLLLLLLLLLLLLLLLLLLLLLLLLRRRRDRRRDDDR", "Step on the hidden forge pad (far west, bottom). The far end is free now, so it carries you into the sealed finish chamber. Walk the mine lane and take the flag."],
        ],
    },
]