"""maps_data.py -- Map data ported from type-is-code-maps.html (source of truth).

Each MAPS entry keeps: name, rows (list of str), start=(row, col),
tokens=[(row, col, text)], solution=[(moves_string, note)].
[row, col] order is kept as-is from the HTML's M array.
Map 1 has the HTML patch applied: row index 3 is "#......#.......F.#".
"""

MAPS = [
    {
        "name": "Map 1 \u00b7 Two rooms, table, door",
        "rows": [
            "##################",
            "#......#.........#",
            "#................#",
            "#......#.......F.#",
            "#......#######D###",
            "#......#.........#",
            "#......T.........#",
            "#......#.........#",
            "##################",
        ],
        "start": (7, 1),
        "tokens": [
            (1, 2, "Path."),
            (1, 3, "solid"),
            (1, 4, "="),
            (5, 10, "Door."),
            (5, 11, "open"),
            (5, 12, "="),
            (2, 10, "False"),
            (6, 3, "True"),
        ],
        "solution": [
            ("UUUUURRRRRRR", "Climb the left room and walk through the open gap into the top-right room."),
            ("URRRD", "Circle round False so you stand on its right side."),
            ("LLLLL", "Push False left, back through the gap, to the cell under the rule slot."),
            ("DLU", "Go under it and push it up: Path.solid = False (table vanishes)."),
            ("LLLDDDD", "Walk to the left of True, in the bottom of the start room."),
            ("RRRRRRRRRR", "Push True right through the old table cell into the bottom-right room."),
            ("DRU", "Slip under and push True up into the Door rule: Door.open = True."),
            ("RUUURR", "Through the door and on to the flag."),
        ],
    },
    {
        "name": "Map 2 \u00b7 Three rooms, NOT vault, trap",
        "rows": [
            "####################",
            "#.....#......#.....#",
            "#.....#......#.....#",
            "#.....#......#.....#",
            "#.....D......X...F.#",
            "#.....###T#T##.....#",
            "#.....#......#.....#",
            "#.....#......#.....#",
            "####################",
        ],
        "start": (7, 1),
        "tokens": [
            (1, 2, "Door."),
            (1, 3, "open"),
            (1, 4, "="),
            (4, 4, "True"),
            (7, 2, "Path."),
            (7, 3, "solid"),
            (7, 4, "="),
            (6, 5, "False"),
            (1, 8, "Trap."),
            (1, 9, "lethal"),
            (1, 10, "="),
            (6, 9, "NOT"),
            (3, 12, "True"),
        ],
        "solution": [
            ("UURRRRD", "Push False down into the Path rule: Path.solid = False. Both tables in the middle room are now walkable."),
            ("LLUURDRUUU", "Push the first True right, then up into the Door rule: Door.open = True."),
            ("DDRRRRRRDDDLL", "Through the door, cross the middle room and drop through a table gap into the vault, ending under NOT."),
            ("UUU", "Push NOT up out of the vault to the row 3."),
            ("LURRDRUU", "Push NOT right 2, then up 2 into the Trap rule slot."),
            ("DDRUU", "Go round the second True and push it up next to NOT: Trap.lethal = NOT True = False."),
            ("DDRRRRR", "Walk over the now-harmless trap and into the flag room."),
        ],
    },
    {
        "name": "Map 3 \u00b7 Serpentine vault",
        "rows": [
            "##################",
            "#.....#.....#....#",
            "#.....#.....#....#",
            "#.....####..#....#",
            "#.....T.....D...F#",
            "#.....#.##..#....#",
            "#.....#.....#....#",
            "#.....#.....#....#",
            "##################",
        ],
        "start": (7, 1),
        "tokens": [
            (2, 1, "Path."),
            (2, 2, "solid"),
            (2, 3, "="),
            (2, 5, "True"),
            (5, 4, "NOT"),
            (1, 7, "Door."),
            (1, 8, "open"),
            (1, 9, "="),
            (6, 10, "NOT"),
            (6, 11, "False"),
        ],
        "solution": [
            ("RRRUUUU", "Push the first NOT up into the Path rule: Path.solid = NOT True = False. The table in the gap disappears."),
            ("DRRR", "Walk through the old table cell into the vault."),
            ("DDDRRR", "Go down the left side and along the bottom to stand under the second NOT."),
            ("UUUUU", "Push NOT up through the wall opening into the Door rule."),
            ("DDDDDRUUUUU", "Go back down, shift one column right and push False up beside it: Door.open = NOT False = True."),
            ("DDRRRRR", "Down to the door row, through the open door and on to the flag."),
        ],
    },
    {
        "name": "Map 4 \u00b7 Swap the values",
        "rows": [
            "#################",
            "#...............#",
            "#...............#",
            "#...............#",
            "#...............#",
            "##.##############",
            "#......X...D...F#",
            "#################",
        ],
        "start": (6, 1),
        "tokens": [
            (2, 10, "Door."),
            (2, 11, "open"),
            (2, 12, "="),
            (2, 13, "False"),
            (2, 14, "True"),
            (1, 3, "Trap."),
            (1, 4, "lethal"),
            (1, 5, "="),
        ],
        "solution": [
            ("RUU", "Climb the gap from the corridor into the big hall."),
            ("RRRRRRRUUURRRR", "Walk to the top row, above the Door rule's False."),
            ("D", "Push False down out of the Door rule (Door.open is back to False for now)."),
            ("URRDDL", "Loop round the right side to stand right of False."),
            ("LLLLLLL", "Push False left along the bottom row of the hall, under the Trap rule."),
            ("DLUU", "Get beneath it and push it up into the Trap rule: Trap.lethal = False."),
            ("DRRRRRRRRRUL", "Cross to the right, get right of True and push it left into the empty slot: Door.open = True."),
            ("DDLLLLLLLLLLLLDD", "Head back to the gap and drop into the corridor."),
            ("RRRRRRRRRRRRR", "Walk over the harmless trap, through the open door, to the flag."),
        ],
    },
    {
        "name": "Map 5 \u00b7 Four chambers, three gates",
        "rows": [
            "#########################",
            "#.....#.....#.....#.....#",
            "#.....#.....#.....#.....#",
            "#.....#.....#.....#.....#",
            "#.....D.....T.....X....F#",
            "#.....#.....#.....#.....#",
            "#.....#.....#.....#.....#",
            "#.....#.....#.....#.....#",
            "#########################",
        ],
        "start": (7, 1),
        "tokens": [
            (1, 1, "Door."),
            (1, 2, "open"),
            (1, 3, "="),
            (6, 4, "True"),
            (4, 2, "False"),
            (6, 7, "Path."),
            (6, 8, "solid"),
            (6, 9, "="),
            (2, 9, "True"),
            (1, 13, "Trap."),
            (1, 14, "lethal"),
            (1, 15, "="),
            (6, 16, "NOT"),
        ],
        "solution": [
            ("RRRUUUUU", "Room 1: push True up into the Door rule (Door.open = True)."),
            ("LLLDD", "Walk round to the left of False."),
            ("RRRRRRRR", "Push False right, through the now-open door, to the middle of room 2."),
            ("URDD", "Get above it and push it down into the Path rule: Path.solid = False. The table gate opens."),
            ("UUUULDD", "Go up to the top row and push the second True down to row 4."),
            ("LDRRRRRRRR", "Get left of that True and push it right through the table cell into room 3 (far right column)."),
            ("LDDDRUUUUU", "Loop under it and push NOT up into the Trap rule slot."),
            ("DDDRUUU", "Go round and push True up beside NOT: Trap.lethal = NOT True = False."),
            ("DDRRRRRR", "Cross the harmless trap into room 4 and reach the flag."),
        ],
    },
    {
        "name": "Map 8 · Vault cathedral · sealed door",
        "rows": [
            "############################################",
            "#.............#.............#.......#.#....#",
            "#.........#...#.............#.......#.#....#",
            "#.............#.......M.....#.......#.#....#",
            "#.............D.............T.......X.D.XF.#",
            "#.............#.............#.......#.#....#",
            "#.M...M...M...BBBBBBBBB.M.M.#.#T#T#.#.#.M.M#",
            "#.....S.....#.B.......B.#...#.#...#.#.#....#",
            "#...MS.SM...M.B.M...M.B.M.M.#.#.M.###.#.M.M#",
            "#.....S...#...B.......B.....#.#...#.#.#....#",
            "#.M...M...M...BBBBBBBBB.M.M.#.#####.#.#.M.M#",
            "############################################",
        ],
        "start": (9, 2),
        "tokens": [
            (2, 3, "Door."), (2, 4, "open"), (2, 5, "="),
            (8, 6, "True"),  (4, 3, "False"),
            (2, 17, "Stone."), (2, 18, "solid"), (2, 19, "="),
            (2, 30, "Trap."), (2, 31, "lethal"), (2, 32, "="),
            (7, 33, "NOT"), (6, 8, "True"),
            (9, 15, "Seal."), (9, 16, "active"), (9, 17, "="),
            (9, 19, "True"), (8, 18, "NOT"),
        ],
        "solution": [
            ("RUUUURUURRUURRRRRRRRRRD",
             "Vault: push NOT down into the Seal rule: Seal.active = NOT True = False."),
            ("ULLLDDDDLLDDLLLLDLDLUUUUULURDRU",
             "Room 1: push NOT up into the Door rule: Door.open = NOT sealed = NOT False = True."),
            ("LLLLDRRRRRRRRRRRRRRRRRDRUU",
             "Push False through the open door and up into the Stone rule: Stone.solid = False."),
            ("DRRRRRRRRRDRRDDDDRRUUUUUU",
             "Enter the trap vault through a stone cell and push NOT up into the Trap rule slot."),
            ("DLLLLLLLLLLLLLLLLLLLLDLLDDLLLUULURRRRRRRRRRRRRRRRRRRRRRRRRRDRUU",
             "Carry True through the door to sit beside NOT: Trap.lethal = NOT True = False."),
            ("DRRRRRRR",
             "Walk over the harmless traps, through the second door, to the flag."),
        ],
        "warp": [[1, 13, 7, 15]],
    },
    {
        "name": "Map 10 · The Relocating Flag (L6)",
        "rows": [
            "##################################################",
            "#M.M...M.M..B...M.....M.B...........B...B........#",
            "#...........B...........B...........B.M.B........#",
            "#M#.........B.........#.B.H.....H...B.#.B...#M...#",
            "#.........#.B.......#...B..#.....#..B...B........#",
            "#M..........B...M.....M.B...........B...B..M...B.#",
            "#...........D...........X...........T...D..X..BFB#",
            "#M..........#...........#.H...#.H...B...BM.....B.#",
            "#.........#.B...........B...........B...B........#",
            "#M..........B.#......#M.B.#......#..B.#.B...#....#",
            "#...........B...........B...........B.M.B........#",
            "#M.M...#.M..B...........B.H.....H...B...B....M...#",
            "##################################################",
            "#.....................................BBBBBBBBBB.#",
            "#..............................H......B..H.HT..B.#",
            "#...........#.......................#.B...H.T..B.#",
            "##.H.......H....#.....................B.H...T..B##",
            "#..............................H......BBBBBBBBBB.#",
            "##################################################",
        ],
        "start": (9, 2),
        "tokens": [
            (2, 2, "Door."), (2, 3, "open"), (2, 4, "="), (2, 5, "False"),
            (9, 8, "True"), (10, 3, "True"),
            (2, 14, "Trap."), (2, 15, "lethal"), (2, 16, "="),
            (9, 17, "NOT"),
            (8, 28, "Stone."), (8, 29, "solid"), (8, 30, "="),
            (10, 29, "Wall."),
            (14, 5, "solid"), (14, 6, "="),
            (16, 7, "False"),
            (14, 20, "Flag."), (14, 21, "moved"), (14, 22, "="),
            (11, 14, "True"),
        ],
        "solution": [
            ("RUUUUUURRRUULDDDLDDDDDLLDRRRDRUUUUUUUURULRRRRRDDDDRRRRRDDDDRUUUUUUUDDDLLLLLLDDDDLLLUUULURRRRRRRRRRDRUUUURRRDRRDDRRRRDDDRUDRRDLDLUULUUULLLLLLLLLLLLLLLLULLULLLLDLDRRRRRRRRRURDLDRRRRRRRRRDRULURRRRRRRRURDD",
             "Original relay: open the door, disarm the trap, then rebuild the Wall rule so Wall.solid = False (plain walls become passable). The fuse idea is gone; the visible flag is now a decoy sealed behind mines."),
            ("ULLLLDDDDDDDDDDDLLLLLLLLLLLLLLLLLLLLUU",
             "Cross the floor wall into the new lower hall. Push its spare False into the Stone rule: Stone.solid = False. Every stone, including the wall of stones inside the hidden chamber, vanishes."),
            ("RUUURRRRRURRRRRRRRRURDDD",
             "Climb back into the first hall (plain walls are passable now). Push the spare True from its corner east along the floor to column 23, then drop it down through the floor wall into the Flag rule: Flag.moved = True. The flag leaps out of its mine ring into the isolated chamber."),
            ("LLLLDDDDLLLLLLLLLLLLLLLLLL",
             "The chamber has no door. Run down and west along the bottom edge to the hidden portal pad in the bottom-left corner nook (the pad in the top-right corner is a decoy)."),
            ("DRRDRRURRR",
             "Weave through the hidden always-lethal mines (they stay armed after the trap is disarmed), pass the vanished stones and step on the relocated flag."),
        ],
        "warp": [[17, 1, 14, 39], [13, 48, 17, 30]],
        "f2": [15, 46],
    },
]
